# Pre-commit configuration for the cookiecutter template itself
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '{{cookiecutter\.project_slug}}/.*'
      - id: end-of-file-fixer
        exclude: '{{cookiecutter\.project_slug}}/.*'
      - id: check-yaml
        exclude: '{{cookiecutter\.project_slug}}/.*'
      - id: check-toml
        exclude: '{{cookiecutter\.project_slug}}/.*'
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
        files: ^(hooks|tests)/.*\.py$
      - id: check-docstring-first
        files: ^(hooks|tests)/.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^(hooks|tests)/.*\.py$
      - id: ruff-format
        files: ^(hooks|tests)/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        files: ^tests/.*\.py$
        additional_dependencies: [types-PyYAML, types-requests, pytest, cookiecutter, tomli]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-ll]
        files: ^hooks/.*\.py$
        types: [python]

  - repo: local
    hooks:
      - id: cookiecutter-json-validate
        name: Validate cookiecutter.json
        entry: python -c "import json; json.load(open('cookiecutter.json'))"
        language: system
        files: cookiecutter.json

      - id: template-test
        name: Run template tests
        entry: python -m pytest tests/ -x -q
        language: system
        pass_filenames: false
        stages: [manual]
